services:
  api:
    volumes:
      - ./.git:/qa-api/.git
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
  db:
    restart: always
  redis:
    restart: always
  # smtp:
  #   restart: always
