default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: password

development:
  <<: *default
  database: <%= ENV['TMP_WORKING_DATABASE'] || 'rails-api_development' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  username: postgres
  password: password
  port: 5432

test:
  <<: *default
  database: rails-api_test
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  username: postgres
  password: password
  port: 5432

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  primary_replica:
    <<: *default
    url: <%= ENV['REPLICA_DATABASE_URL'] %>
    replica: true
